# for simplicity we are checking compilation and testing everything on the Ubuntu environment only.

name: testing_changes

on: 
    push:
      branches-ignore:
        - 'main'
        - 'master'
        - 'draft/*'
    pull_request:
      types: [opened, reopened, synchronize]
    release:
      types: [created, edited]
    workflow_dispatch:
      inputs:
        # See https://hub.docker.com/r/firebirdsql/firebird for supported versions/tags
        # and further details on input environment variables
        # you may only define up to 10 `inputs` for a `workflow_dispatch` event
        version:
          description: 'Version of firebirdsql to use: latest, 5, 5.0.2, 5-noble, 5-jammy, 4, 4.0.5, 3, 3.0.9. See: firebirdsql/firebird for a complete list of tags.'
          required: false
          default: 'latest'
        port:
          description: 'Optional port published in the host for connecting to the database. Default: 3050.'
          required: false
          default: '3050'
        firebird_database:
          description: 'Optional name for creating a database inside the container'
          required: false
          default: ''
        firebird_user:
          description: 'Optional name for creating a user that is database owner inside the container'
          required: false
          default: ''
        firebird_password:
          description: 'Optional password for the user created'
          required: false
          default: ''
        firebird_root_password:
          description: 'Default sysdba user password, if left blank Firebird installer generates a one-off password for SYSDBA instead'
          required: false
          default: ''
        timezone:
          description: 'Server TimeZone. (i.e. America/Sao_Paulo)'
          required: false
          default: ''
        firebird_conf:
          description: 'Comma separated list of settings to be set in `firebird.conf`. E.g.: `ConnectionTimeout=180,DeadlockTimeout=10`. See: https://firebirdsql.org/rlsnotesh/config-fb-conf.html'
          required: false
          default: ''
        container_name:
          description: 'The name for tagging the container. Default: firebirdsql'
          required: false
          default: 'firebirdsql'
        network_name:
          description: 'Optional name of the network for connecting the container'
          required: false
          default: ''

jobs:
  ci:
    name: ci-testing_changes
    strategy:
      # max-parallel: 1
      matrix:
        target: [latest, 5, 5.0.2, 5-noble, 5-jammy, 4, 4.0.5, 3, 3.0.9]
        os: [ "ubuntu-latest" ]
        #TODO: os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout source code on event ${{ github.event_name }} triggered by '${{ github.sha }}'
        if: github.event_name != 'release'
        uses: actions/checkout@v3

      - name: Testing changes with FirebirdSQL version ${{ matrix.target }} on ${{ github.event_name }} triggered by '${{ github.sha }}'
        if: github.event_name != 'release'
        uses: ./ # Uses an action in the root directory
        with:
          version: '${{ matrix.target }}'
          firebird_database: 'my_database.fdb'
          firebird_user: 'my_user'
          firebird_password: 'my_password'

      - name: Testing release with FirebirdSQL version ${{ matrix.target }} triggered by version '${{ github.event.release.tag_name }}'
        if: github.event_name == 'release'
        uses: juarezr/firebirdsql-github-action@master
        with:
          version: '${{ matrix.target }}'
          firebird_database: 'my_database.fdb'
          firebird_user: 'my_user'
          firebird_password: 'my_password'

      - name: Install FirebirdSQL clients
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends firebird3.0-utils libfbclient2

      - name: Testing Connection and Query to ${{ matrix.target }}
        run: |
          for i in {0..120} ; do nc -z localhost 3050 && echo "Up: ${i} secs" && break; sleep 1; done
          echo 'select * from rdb$database;' | isql-fb -bail -quiet -z -user my_user -password my_password 'localhost:/firebird/data/my_database.fdb'

      - name: Stop Container
        run: |
          docker rm --volumes --force firebirdsql

# end of file
